dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-11/run.sh | bash
notifications:
  slack:
    rooms:
      secure: oLrO50XJvQuIDjFVxqH4DZxh9q8EjESz0jgsKRBFVnu03fk977xJ00Gty2exoo74ZnHpXyaOeQOcNzkuSEaM2c95JxfgzgoB+no9yddxET6YxeUli7ZclnWpWLIcyZPmcrjoU7Z1wi+GaHTxRLIz1syiNL3QeROcza6fnuN4O812zQ/dNrh2nj6EePW8Y+ZIlmz/+EBCFnGr63Ik3nr7r23RjHCwT7Vzex3606/QDm0dupV74XT5YHTw8+GPEt9owqmM8Ra6/f/hRvOiYS6WkDT2D45ZfT68hDyiMHWiwJpWmvF9CeahWxcGN+dQpzcQUWbfesSbD7CvI8wyzMyODxA3OWiSOXeavt0Z9CifjOzvqYf5Hot3gv3Zn0HPTCtmw2oU8YR8Gt1Cn6SwdwquQ+JNt43JskXE1xUdGbica6SQ0rtn0KYTqNpcKDVUiyqL3UKaDUxLj6+1cL0SC8WtNGfpD2JnxFhBu5oF82OXBPi1NakFdwNeSqsogqCUkhTL3WgCYqr65GnCOlZF0LQSobRpcy4dRm7s3XyuSPc7YNRjVxqOGMICE59R6EJ6hMGP8rE+WnkiG73Tf08yURPJ0VH9wIvOV6m0Tg2wSFWS+VI4WE92HNX0QqWZqTnqW99L4dCM1tYwZWAnIe+hFYpW3IQI9JLMyC+op5BbcszT79A=
<<<<<<< HEAD

=======
>>>>>>> master
